[main]
# Optional: Set a clean, modern font and padding
font=monospace:size=11
pad=8x8                             # Generous inner padding

[colors]
alpha=0.95
background=2d2b36
foreground=ffffff

regular0=2d2b36
regular1=ff6e6e
regular2=665ca8
regular3=ffffff
regular4=473f7a
regular5=887ebc
regular6=484654
regular7=ffffff

bright0=484654
bright1=ff8787
bright2=887ebc
bright3=ffffff
bright4=665ca8
bright5=aaa2d1
bright6=67647a
bright7=ffffff

