[main]
# Optional: Set a clean, modern font and padding
font=monospace:size=11
pad=10x10                             # Generous inner padding

[colors]
alpha=0.95
background=000000
foreground=ffffff

# normal
regular0=1c1c1c  # black
regular1=bcbcbc  # red
regular2=8a8a8a  # green
regular3=afafaf  # yellow
regular4=9e9e9e  # blue
regular5=d0d0d0  # magenta
regular6=e4e4e4  # cyan
regular7=ffffff  # white

# bright
bright0=4e4e4e   # bright black
bright1=ffffff   # bright red
bright2=ffffff   # bright green
bright3=ffffff   # bright yellow
bright4=ffffff   # bright blue
bright5=ffffff   # bright magenta
bright6=ffffff   # bright cyan
bright7=ffffff   # bright white
